Script started on Sat 05 Feb 2022 03:04:09 PM CST
[?1034hbash-4.2$ cd ~/cs161/root
bash-4.2$ ./sys161 kernen[Kl
sys161: System/161 release 1.14, compiled Feb  4 2022 12:43:50

OS/161 base system version 1.10
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Put-your-group-name-here's system version 0 (ASST0 #1)

Cpu is MIPS r2000/r3000
1872k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

OS/161 kernel [? for menu]: p /sbin/poweroff <return>
Operation took 0.000162800 seconds
OS/161 kernel [? for menu]: Shutting down.
The system is halted.
sys161: 900715571 cycles (7865302k, 18u, 892850251i)
sys161: 4235 irqs 6 exns 0r/0w disk 26r/667w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 36.017406 seconds (25.0078 mhz)
sys161: Elapsed virtual time: 36.028622840 seconds (25 mhz)
bash-4.2$ exit
exit

Script done on Sat 05 Feb 2022 03:05:31 PM CST
